# Generated by Django 6.0 on 2026-02-21 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('admin_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer_name', models.CharField(max_length=60)),
                ('lawyer_email', models.EmailField(max_length=254, unique=True)),
                ('lawyer_password', models.CharField(max_length=30)),
                ('lawyer_photo', models.FileField(upload_to='Assets/LawyerPhoto/')),
                ('lawyer_proof', models.FileField(upload_to='Assets/LawyerProof/')),
                ('lawyer_address', models.CharField(max_length=70)),
                ('lawyer_status', models.CharField(max_length=10)),
                ('lawyer_qualification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('plan_duration', models.CharField(max_length=50)),
                ('plan_price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_lawyercategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_category')),
                ('lawyer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_lawyer')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_district')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_lawyer',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_place'),
        ),
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_file', models.FileField(upload_to='Assets/RequestFile/')),
                ('request_status', models.CharField(max_length=10)),
                ('mode_status', models.CharField(default=1, max_length=10, null=True)),
                ('request_date', models.CharField(max_length=30)),
                ('request_type', models.CharField(max_length=10)),
                ('request_fee', models.CharField(max_length=10)),
                ('lawyer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_lawyer')),
                ('level_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_level')),
                ('type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_type')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_requestfee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestfee_amount', models.CharField(max_length=50)),
                ('requestfee_details', models.CharField(max_length=100)),
                ('request_status', models.IntegerField(default=0)),
                ('request_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_request')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_requestreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestreport_file', models.FileField(upload_to='Assets/RequestreportFile/')),
                ('requestreport_details', models.CharField(max_length=200)),
                ('request_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_request')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('schedule_time', models.TimeField()),
                ('schedule_venue', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule_link', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule_status', models.IntegerField(default=0)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_request')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_category')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_subtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype_name', models.CharField(max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_type')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=30)),
                ('user_photo', models.FileField(upload_to='Assets/UserPhoto/')),
                ('user_proof', models.FileField(upload_to='Assets/UserProofs/')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_startdate', models.CharField(max_length=30)),
                ('subscription_enddate', models.CharField(max_length=30)),
                ('plan_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_plan')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_request',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user'),
        ),
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_count', models.CharField(max_length=50)),
                ('rating_comment', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=50)),
                ('complaint_content', models.CharField(max_length=100)),
                ('complaint_reply', models.CharField(max_length=50)),
                ('complaint_status', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
    ]
