# Generated by Django 6.0 on 2026-02-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_plan',
            name='plan_price',
        ),
        migrations.AlterField(
            model_name='tbl_plan',
            name='plan_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_subscription',
            name='subscription_enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tbl_subscription',
            name='subscription_startdate',
            field=models.DateField(),
        ),
    ]
