# Generated by Django 6.0 on 2026-02-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_tbl_plan_plan_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_plan',
            name='plan_price',
            field=models.IntegerField(null=True),
        ),
    ]
