# Generated by Django 6.0 on 2026-03-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_tbl_plan_plan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_reply',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_status',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
