# Generated by Django 6.0 on 2026-03-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_tbl_complaint_complaint_reply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_planpurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.tbl_user')),
            ],
        ),
    ]
