# Generated by Django 6.0 on 2026-03-05 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_tbl_planpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_lawyer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.tbl_category'),
        ),
    ]
