# Generated by Django 6.0 on 2026-03-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_tbl_lawyer_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_lawyer',
            name='category',
        ),
        migrations.AddField(
            model_name='tbl_lawyer',
            name='categories',
            field=models.ManyToManyField(blank=True, to='server.tbl_category'),
        ),
    ]
