# Generated by Django 6.0 on 2026-03-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_remove_tbl_lawyer_category_tbl_lawyer_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_rating',
            name='rating_count',
            field=models.IntegerField(null=True),
        ),
    ]
